#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PluginRegistration.Core.Model.OptionSets
{
	// CLEANED (per request): Removed large number of unused generated OptionSets 
	// (ComponentState, all CustomAPI_* , most SdkMessage* detailed/internal enums, etc.).
	// Early bound will NOT be re-generated.
	//
	// Registration summary:
	//   - Assembly mode (.dll):  pluginassembly.content = base64(DLL), sourcetype=0
	//   - Package mode (.nupkg): pluginpackage.content = base64(full .nupkg)
	//     Dataverse then creates linked pluginassembly records (packageid + sourcetype ~4).
	//
	// We rely primarily on packageid for distinguishing, not these enums.
	// Only minimal enums kept for reference.

	/// <summary>
	/// Plugin assembly isolation mode.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum PluginAssembly_IsolationMode
	{
		[System.Runtime.Serialization.EnumMemberAttribute()]
		External = 3,
		[System.Runtime.Serialization.EnumMemberAttribute()]
		None = 1,
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Sandbox = 2,
	}

	/// <summary>
	/// Plugin assembly source type. Value 4 is associated with Plugin Packages.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum PluginAssembly_SourceType
	{
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Azurewebapp = 3,
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Database = 0,
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Disk = 1,
		[System.Runtime.Serialization.EnumMemberAttribute()]
		FileStore = 4,
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Normal = 2,
	}

	/// <summary>
	/// Plugin Package state.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum pluginpackage_statecode
	{
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 0,
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 1,
	}

	/// <summary>
	/// Plugin Package status code.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum PluginPackage_StatusCode
	{
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 1,
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 2,
	}
}
#pragma warning restore CS1591
